### PR TITLE
Add signature veryfing with lovasoa/sanipasse strategy.

### PR DESCRIPTION
**Pull request by rebuglio**
Hi! I write few lines of code, a simplified version of the great lovasoa/sanipasse, with the same dependencies. I think it is faster and more readable, using certificate in json format.

It would be usefull if Ministero della Salute make a pubblic API to fecth the certificates in this format. There is a discussion about this: https://github.com/lovasoa/sanipasse/blob/master/fetch_certificates.js

### CODE REVIEW

**Comment by astagi** [comment]
Hi @rebuglio this PR looks great! Could you please add tests for this new method?

**Review by astagi — CHANGES_REQUESTED** [review]
Tests are needed for this feature

**Comment by rebuglio** [comment]
Test added, and add better error handling

**Review by astagi — APPROVED** [review]
Looks great! Thanks @rebuglio

**Pull request merged**
